name: Read milestone file
author: mmagician
description: 'Read file contents'
inputs:
  path:
    description: 'File path'
    required: true
  strict:
    description: 'Strict mode: fails instead of warning'
    required: false
    default: 'true'
outputs:
  application_document:
    description: 'Link to application PR'
  milestone_number:
    description: 'Milestone number'
  is_maintenance:
    description: 'True IFF the delivery is for a maintenance grant'
runs:
  using: 'node20'
  main: 'dist/index.js'
